### ISSUE TITLE
Support existing Cloudformation Stack

### ISSUE THREAD

**Issue by robdimsdale** [rosenhouse/tubes#5]
This follows on from the conversation in #3 . I'd like to be clear that I'm not necessarily asking for a new feature set, but I think there's a couple of interesting workflows that tubes doesn't handle that it potentially could:
1. I setup some infrastructure by consuming a cloudformation stack provided to my by a third-party for a product that tubes doesn't know or care about.
   -1. I am happy with the infrastructure and I have VMs running or something similar that I don't want to be torn down.
2. I would like to leverage tubes to add a bosh director (or a concourse, or anything else that tubes does support). How can I achieve this goal?

A similar use case would be to take a third-party cloudformation script and add whatever tubes needs to that, to form a composition of third-party plus bosh director or concourse.

I could be persuaded, in both cases, that these use-cases aren't realistic, that why would you want to add a BOSH director or concourse deployment to the same VPC as some existing software that isn't managed by BOSH or deployed via concourse?

I could also be persuaded that this massively increases the complexity of tubes, as it now has to make intelligent decisions about what parts of the existing infrastructure it can piggyback onto, and what parts it can't. In fact this might be essentially impossible without the user explicitly saying things like: "Tubes, you must use VPC x, and re-use subnet Y, but you can't use subnet Z because the security groups don't quite match what you're looking for to deploy BOSH and you must use ELB A but cannot re-use ELB B" etc

**Comment by rosenhouse** [comment]
My big goal with this project is to minimize the amount of user-facing configuration.  I have the (perhaps naive) belief that a simple, opinionated workflow will meet the needs of a _lot_ of people & teams.  All we really need is test-driven, continuously-integrated plumbing (_tubes_) between the various tools (cloudformation, route53, bosh-init, bosh) and various sources of truth (bosh.io, github releases).

But I'll readily admit I may have tunnel vision here -- I'm mostly thinking of recent experiences on CF LA & MEGA, and wanting a Concourse server for personal projects.

I'd be very interested to hear about use cases where spinning up a separate VPC is not a good choice and instead one wants BOSH + extras to ride on top of an existing VPC.  I'll probably have follow-up questions from there, aimed at identifying the minimal set of shared config between the existing VPC and the tubes-created infrastructure.

**Comment by robdimsdale** [comment]
So I've been thinking about this for a few days, and I can't come up with any realistic situation that tubes doesn't solve that I think it should.

At some level I can see a few scenarios like I described above - some third-party provides some of the infrastructure, perhaps I want to add a bosh director to it but I don't control the VPC, etc. But I don't think it's reasonable for tubes to try to solve that, certainly not yet.

I'm going to close this issue. If I have any insights I'll share them in a new issue.
